### ISSUE TITLE
global: initial implementation

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-opendefinition#1]
Create a module similar to Invenio-OpenAIRE that can import http://licenses.opendefinition.org/licenses/groups/all.json

Required:
- [ ] JSON schema for licenses.
- [ ] Elasticsearch mapping.
- [ ] CLI command ``<cmd> opendefinition loadlicenses``
- [ ] Celery tasks: 1) Download JSON and send tasks to create records 2) Create records + PIDs
- [ ] JSONResolver so that we can resolve ``"license": {"$ref": "http://dx.zenodo.org/licenses/<pid>"}`` without making HTTP requests.

**Comment by jirikuncar** [comment]
> `<cmd> opendefinition loadlicenses`

I would go for simple `<cmd> opendefinition load`
