### ISSUE TITLE
mapping: improve suggest indexing to find "Zero/CC0" 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-opendefinition#20]
From zenodo/zenodo#986

Finding "Creative Commons Zero - CC0 1.0" license is hard to find.

The following searches don't bring it up:

"Zero"
"CC0"
You can find it with "Creative Commons Zero", which is not the first thing people look for.

**Comment by carlinmack** [comment]
Can be found with both now
![image](https://github.com/user-attachments/assets/c5bbc324-d836-45e5-a86e-6019328eb328)
![image](https://github.com/user-attachments/assets/bfddad9c-b80d-4846-bedd-67d76b95f737)
